import type { AssistantPhase, BuiltInSceneMode } from "@ai-vision/shared";

export type SceneModeProfile = {
  label: string;
  description: string;
  focus: string[];
  examples: string[];
  nextSteps: string[];
};

export const sceneModeCopy: Record<BuiltInSceneMode, SceneModeProfile> = {
  general: {
    label: "通用视觉对话",
    description: "适合自由询问当前画面、最近变化和连续追问。",
    focus: ["当前画面", "最近变化", "连续追问"],
    examples: ["你现在看到什么？", "刚才发生了什么？", "我手里拿的是什么？"],
    nextSteps: ["连接摄像头和麦克风", "让 AI 先观察几秒", "直接语音或打字提问"],
  },
  action: {
    label: "动作理解助手",
    description: "重点理解最近几秒的动作、手势和物体移动。",
    focus: ["动作变化", "手势判断", "物体移动"],
    examples: ["我刚才做了什么动作？", "我有没有拿起东西？", "我的手势有什么变化？"],
    nextSteps: ["做一个明显动作", "等待右侧出现最近变化", "询问刚才发生了什么"],
  },
  interview: {
    label: "演讲/面试练习助手",
    description: "观察姿态、视线、手势和表达状态，给出简短反馈。",
    focus: ["坐姿视线", "手势状态", "表达反馈"],
    examples: ["我刚才表现怎么样？", "我的坐姿和视线自然吗？", "我有哪些可以改进的地方？"],
    nextSteps: ["对着镜头说一段话", "保持自然手势", "让 AI 给出简短改进建议"],
  },
  life: {
    label: "生活提醒助手",
    description: "关注物品变化、桌面状态和需要注意的轻量提醒。",
    focus: ["物品变化", "桌面状态", "轻量提醒"],
    examples: ["画面里有什么需要注意？", "桌面上有什么变化？", "我是不是忘了什么东西？"],
    nextSteps: ["让桌面或物品进入画面", "移动或拿起关键物品", "询问需要注意的地方"],
  },
};

export const appCopy = {
  initialAssistantMessage:
    "准备好了。连接摄像头和麦克风后，我可以一边看画面，一边听你说话；你也可以直接打字提问。",
  mediaConnectedMessage: "摄像头和麦克风已连接。",
  mediaVideoOnlyMessage:
    "摄像头已连接，但麦克风不可用；可以先使用文字提问或画面分析。",
  cameraSwitchedMessage: "已切换摄像头设备。",
  realtimeConnectedMessage: "语音识别已启动，可以开始说话。",
  backendOnlineMessage: "后端服务已连接。",
  backendOfflineMessage:
    "后端服务未连接，请先启动 NestJS 服务后再进行语音问答或画面分析。",
  voiceDisabledBackendOffline:
    "摄像头预览可继续使用；后端未运行时，问题不会发送。",
  realtimeConnectionError:
    "语音通道连接失败，请确认后端服务、DashScope Key 和浏览器授权正常。",
  cameraPermissionError: "无法连接摄像头，请检查浏览器授权后重试。",
  cameraDeviceBusyError:
    "摄像头可能正被其他程序占用，请关闭会议软件、相机应用或浏览器其他页面后重试。",
  cameraNotFoundError:
    "没有找到可用摄像头，请确认设备已接入并允许浏览器访问。",
  cameraPermissionDeniedError:
    "浏览器拒绝了摄像头权限，请在地址栏左侧站点设置中允许摄像头后重试。",
  microphoneUnavailableMessage:
    "麦克风不可用或未授权，本次会话已降级为摄像头加文字输入模式。",
  microphonePermissionDeniedError:
    "浏览器拒绝了麦克风权限，请在地址栏左侧站点设置中允许麦克风后重试。",
  microphoneNotFoundError:
    "没有找到可用麦克风，请确认设备已接入并在系统中启用。",
  microphoneBusyError:
    "麦克风可能正被其他程序占用，请关闭会议软件、录音软件或浏览器其他页面后重试。",
  cameraSecureContextError:
    "浏览器只允许在 localhost 或 HTTPS 页面使用摄像头和麦克风。请用 http://localhost:5173 打开，或为局域网地址配置 HTTPS。",
  cameraPlaybackError:
    "摄像头已授权，但视频播放被浏览器阻止；请刷新页面后重试。",
  cameraFrameWaiting:
    "摄像头已授权，正在等待视频首帧。如果一直黑屏，请确认没有其他程序占用摄像头。",
  cameraMutedState: "无画面",
  cameraNotReadyMessage: "摄像头画面还没有准备好，请稍等一下再分析。",
  autoVisionCaptureMessage:
    "正在读取当前摄像头画面，并作为这次问题的视觉上下文。",
  autoVisionCaptureFailed:
    "这次没有成功读取摄像头画面，将先用已有画面继续回答。",
  visionAnalyzeError:
    "画面分析失败，请确认后端服务和 DashScope 配置正常。",
  actionAnalyzeError:
    "动作序列分析失败，请确认后端服务和 DashScope 配置正常。",
  conversationError:
    "问题发送失败，请确认后端服务正在运行。",
  sessionEndError: "会话结束请求没有成功，但本地设备已经关闭。",
  visionContextSynced: "最新画面已准备好用于下一次回答。",
  visionContextSyncFailed:
    "画面会在下一次问题中作为上下文发送。",
  speechUnsupported: "当前浏览器不支持语音识别，请使用 Chrome 或 Edge 测试。",
  speechRecognitionError:
    "浏览器语音识别启动失败，但摄像头和文字提问仍可继续使用。",
  title: "视觉对话工作台",
  currentSession: "当前会话",
  historyTitle: "历史记录",
  historyEyebrow: "Archive",
  historyDescription: "查看已结束会话、对话内容和最后一帧。",
  historyCollapsedHint: "点击展开历史会话",
  historyExpand: "展开",
  historyCollapse: "收起",
  historyCountPrefix: "共 ",
  historyCountSuffix: " 条",
  historyDetailTitle: "会话详情",
  historyClose: "关闭",
  historyBack: "返回列表",
  historyLoading: "正在加载历史记录...",
  historyEmpty: "还没有已结束的历史会话。",
  historyLoadError: "历史记录加载失败，请确认后端和数据库正常。",
  historyNoEndTime: "结束时间未知",
  historyFinalFrame: "会话最后一帧",
  historyHasFinalFrame: "已保存最后一帧",
  historyNoFinalFrame: "封面未保存",
  historyMessagesUnit: " 条消息",
  historyVisionRequestsUnit: " 次视觉请求",
  realtimeLabel: "Qwen Omni Voice + Vision",
  stageTitle: "边看边听，实时回应",
  cameraOnline: "摄像头在线",
  cameraStarting: "摄像头启动中",
  cameraOffline: "摄像头离线",
  micOnline: "麦克风在线",
  micMuted: "麦克风静音",
  backendOnline: "后端在线",
  backendOffline: "后端离线",
  backendUnknown: "后端检测中",
  videoStreamConnected: "视频观察中",
  videoStreamConnecting: "视频连接中",
  videoStreamFallback: "视频降级",
  videoStreamIdle: "视频待机",
  cameraDeviceLabel: "摄像头",
  cameraDevicePlaceholder: "授权后显示设备",
  unknownCamera: "摄像头",
  emptyVideo: "等待摄像头授权",
  connect: "连接设备",
  connectTitle: "连接摄像头和麦克风",
  toggleMic: "麦克风",
  toggleMicTitle: "切换麦克风",
  toggleCamera: "摄像头",
  toggleCameraTitle: "切换摄像头",
  analyzeFrame: "分析画面",
  analyzeFrameTitle: "分析当前画面",
  autoObserve: "自动观察",
  autoObserveTitle: "自动连续抽帧更新视觉上下文",
  interruptSpeech: "停止回复",
  interruptSpeechTitle: "停止当前播报并继续听你说话",
  replaySpeech: "重新说一遍",
  replaySpeechTitle: "重播上一条 AI 回复，不重新请求模型",
  followUp: "继续追问",
  followUpTitle: "聚焦文字输入框，继续补充你的问题",
  endSession: "结束会话",
  endSessionTitle: "结束会话",
  currentViewTitle: "AI 当前观察",
  recentActionTitle: "刚才发生了什么",
  emptySummary:
    "还没有可用画面。连接摄像头后，我会在这里概括当前看到的内容。",
  emptyActionTimeline:
    "还没有明显变化。做一个动作、移动物品或等待自动观察几秒后，这里会显示最近发生的事。",
  updatedAt: "更新于",
  waitingFirstFrame: "等待画面",
  confidenceNoteLabel: "可信度",
  voiceStatusTitle: "语音状态",
  voiceStatusListening: "正在听",
  voiceStatusHeard: "已听到",
  voiceStatusThinking: "正在思考",
  voiceStatusSpeaking: "正在回复",
  voiceStatusIdle: "等待开始",
  voiceStatusError: "需要处理异常",
  voiceHintListening: "你可以直接说话，也可以在左侧打字。",
  voiceHintThinking: "正在结合画面和问题生成回复。",
  voiceHintSpeaking: "AI 正在回复，可打断或重播。",
  voiceHintIdle: "连接设备后即可开始语音对话。",
  voiceHintError: "请检查设备授权或后端服务状态。",
  heardPrefix: "已听到：",
  followUpPlaceholder: "继续追问上一轮内容...",
  visionContextSyncLabels: {
    idle: "等待观察",
    pending: "准备中",
    synced: "已准备",
    failed: "等待下一次提问",
  },
  assistantPanelLabel: "Scene Assistant",
  customModeLabel: "自定义",
  customModeEmptyTitle: "创建你的专属场景",
  customModeEmptyDescription:
    "填写一个角色卡，让 AI 按你的场景目标理解画面和回答问题。",
  customModeEditTitle: "自定义模式",
  customModeLimitHint: "最多保存 5 个自定义模式，保存在当前浏览器。",
  customModeSaved: "自定义模式已保存。",
  customModeDeleted: "自定义模式已删除。",
  customModeCreate: "新建模式",
  customModeSave: "保存模式",
  customModeDelete: "删除模式",
  customModeSelect: "选择模式",
  customModeName: "模式名称",
  customModeDescription: "适用场景",
  customModeRole: "角色身份",
  customModeMission: "核心任务",
  customModeStyle: "回答风格",
  customModeFocus: "关注重点",
  customModeExamples: "推荐问题",
  customModeNextSteps: "演示建议",
  customModeGuardrail: "边界要求",
  customModeListHint: "每行一条，最多 5 条。",
  demoQuestionsTitle: "推荐提问",
  nextStepsTitle: "演示建议",
  observationTitle: "当前观察",
  changeTitle: "最近变化",
  noObservationYet: "连接摄像头后，这里会显示 AI 对当前画面的自然观察。",
  noChangeYet: "暂时还没有捕捉到明显动作。你可以挥手、拿起物品或转头试试。",
  askQuestionTitle: "发送这个推荐问题",
  costDebugTitle: "成本与调试",
  costDebugCollapsed:
    "低成本观察中：本地采样、静止跳过、云端按需分析。",
  costDebugExpanded:
    "这些指标用于答辩说明端云协同策略，默认折叠以保持 demo 界面干净。",
  showDebug: "展开指标",
  hideDebug: "收起指标",
  metricVisionRequests: "视觉请求",
  metricLowDetail: "低细节",
  metricHighDetail: "高细节",
  metricCostLevel: "成本等级",
  metricAutoVisionRequests: "自动抽帧",
  metricSkippedFrames: "跳过帧",
  metricLastAutoVisionAt: "最近自动更新",
  metricFrameFingerprint: "帧指纹",
  metricActionSamples: "本地采样",
  metricDedupedActionFrames: "动作跳过",
  metricActionSequenceRequests: "动作分析",
  metricLastActionTimelineAt: "最近动作更新",
  metricActionBuffer: "动作缓冲",
  metricVideoStreamStatus: "视频流",
  metricStreamedFrames: "流式帧",
  metricStreamBuffer: "流缓冲",
  metricStreamCloudAnalyses: "云端分析",
  metricStreamTimelineAnalyses: "动作成功",
  metricStreamTimelineErrors: "动作失败",
  metricLastVideoStreamAt: "最近流更新",
  metricLastStreamError: "最近流错误",
  noAutoVisionYet: "暂无",
  fingerprintReady: "已建立",
  fingerprintPending: "等待中",
  costStrategyLabel: "Cost Strategy",
  strategies: [
    "浏览器本地 2 FPS 采样，不等于云端 2 FPS 调用",
    "低变化帧在本地去重，不上传",
    "WebSocket 只推送压缩后的关键帧",
    "云端按 3-10 秒节流分析短序列",
    "图片压缩到 768px 宽",
    "默认 detail: low",
    "每分钟限制自动视觉请求次数",
    "页面不可见、AI 播报或后端离线时暂停观察",
    "重新说一遍只重播本地 TTS，不重新调用模型",
    "自定义场景只改变同一次对话 prompt，不增加额外调用",
  ],
  costLevels: {
    low: "低",
    medium: "中等",
    high: "偏高",
  },
} as const;

export const phaseLabels: Record<AssistantPhase, string> = {
  idle: "空闲",
  connecting: "连接中",
  listening: "聆听中",
  thinking: "思考中",
  speaking: "回复中",
  error: "异常",
};
